
GET http://localhost:3001/sellers
###
GET http://localhost:3001/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJpc2FhY2lzbWFlbHgxNEBnbWFpbC5jb20iLCJ0eXBlIjoxLCJpYXQiOjE2MjAwNTQ5OTh9.RPEw-MFNz5UZYnygeUvLraFhp67QQLeaxN8cdAqVfm0

### Get one seller
GET http://localhost:3001/sellers/1

### Get categories
GET http://localhost:3001/categories

### Get one categories
GET http://localhost:3001/categories/1

### Get questions
GET http://localhost:3001/questions

### Get one question
GET http://localhost:3001/questions/1

### Get answers
GET http://localhost:3001/answers

### Get one answer
GET http://localhost:3001/answers/1

### Get descr
GET http://localhost:3001/descriptions/

### Get one desc
GET http://localhost:3001/descriptions/by-product/1
### Get one desc
GET http://localhost:3001/products