PATCH http://localhost:3001/sellers/1
Content-Type: application/json

{
    "user_id":1,
    "name":"Store This",
    "description":"We have everething",
    "direction":"",
    "rank":0
}

### Update category
PATCH  http://localhost:3001/categories/1
Content-Type: application/json

{
    "category":"Cellphones"
}

### coment
PATCH http://localhost:3001/coments/2
Content-Type: application/json

{
    "product_id":1
}

###Login

PATCH  http://localhost:3001/users/change-password/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJpc2FhY2lzbWFlbHgxNEBnbWFpbC5jb20iLCJpYXQiOjE2MjAwNDU5NzF9.o28AXUPruvOh8xOQZmOxFDWPiUMe-ouHveMnIzuSDgo

{
    "new_pwd":"1234",
    "old_pwd":"1234"
}